### ISSUE TITLE
(imixs-office-workflow) - WildFly deploy/startup error

### ISSUE THREAD

**Issue by asouzamax** [imixs/imixs-marty#136]
"Can not set org.imixs.workflow.engine.WorkflowSchedulerService field org.imixs.marty.workflow.WorkflowSchedulerServlet.workflowSchedulerService to org.imixs.workflow.engine.WorkflowSchedulerService"

That error happens when I try to start the imixs-office-workflow.
Version imixs-workflow-engine is 4.0.1-SNAPSHOT.

**Comment by rsoika** [comment]
What exactly have you done? 
Have you deployed imixs-office-workflow.ear on wildfly? Which version did you use.
What did you mean with 'that error happens when you try to start imixs-office-workflow?
Have you deployed the ear successfully? Did you see the login screen?
Or did you have a deployment problem? In this case please post the deployment messages from the sever.log, so we can see what went wrong.

**Comment by asouzamax** [comment]
I'm trying to mount the develop environment in my machine, importing all projects on my eclipse workspace. All maven builds are passed ok! but in the moment of start the WIldfly(9.0.2_final) the error happens, I think the deploy don't work fine! 
My log file is attached and my workspace screenshot too!

[jbossLog.txt](https://github.com/imixs/imixs-marty/files/555715/jbossLog.txt)
![workspace screenshot](https://cloud.githubusercontent.com/assets/3420209/19766734/3f98f1f6-9c2e-11e6-9b75-d99d80b86f64.png)
![workspace screenshot_001](https://cloud.githubusercontent.com/assets/3420209/19766815/9e11e8be-9c2e-11e6-8b64-c04162db7cfe.png)

**Comment by rsoika** [comment]
Hi,
ok this all looks not too bad. A reason why the WorkflowSchedulerServlet did not start, can be the security configuration. It is important that you provide a security domain matching the secuirty-domain described in the jboss-ejb3.xml (in your ejb module imixs-office-workfow-ejb.jar) and also the jboss-web.xml in your web modules. The default name of the security realm is 'imixsrealm' (but you can change your configuration)
On wildfly server you should also provide a role-mapping properties file matching the name of your security realm (e.g. imixsrealm.properties). 

You will find information about the deployment details here:
http://www.imixs.org/marty/install/wildfly.html
and here:
http://www.imixs.org/doc/deployment/wildfly.html

The problem with a missing security configuration in jboss is, that you will not notice any meaningful error message in your log file. You need to change your logger settings first. You can set the log level for _org.jbos.security_ to TRACE. Stop the server, add the following log category into the _standalone.xml_ file and restart the server:

     <logger category="org.jboss.security">
        <level name="TRACE"/>
     </logger>

**Comment by asouzamax** [comment]
Ok...resolved! thank you!

**Comment by rsoika** [comment]
Please note that version 3.0.0 is still under development, but I think we will release this new major version in a view days.
