### ISSUE TITLE
ProfileService and SearchController

### ISSUE THREAD

**Issue by chrisw14** [imixs/imixs-marty#202]
Hi Ralph,

I have a difficult question to the ProfileService combined with the SearchController:

If a user is logged in with his username "max" and his displayName (of ProfilesService) "Max Mustermann" and creates a workitem, so the $creator is "max". How can I now search for "Mustermann" and finding the workitem of "max"? Didn't found this issue in the ProfileService or in the SearchController.

Joining the profile to the search term would be possible but expensive...

Thank you!

Cheers
Chris

**Comment by rsoika** [comment]
Your application should not deal with the displayname. The displayname is not stored in a workitem as you have seen. Only the userid. Why should a user need to search for the display name?
Of course the display name would be usually found because it is mostly part of the field 'txtworkflowhistory' if you use the tag `<username>....</username>`

In case you need exactly search for workitems created by 'Max Mustermann' than you can provide a extra search field using the Marty-UserInput (http://www.imixs.org/marty/ui/userinput.html). The user can first select a userid which can be used to created a structured search query.

**Comment by chrisw14** [comment]
> Why should a user need to search for the display name?

If the userid doesn't represent the real name of the user because it's a random value for security reasons and somebody want to search for the name of the user. It would confuse a user if there is no search result but he can see the displayname in a list...

>  Of course the display name would be usually found because it is mostly part of the field 'txtworkflowhistory' if you use the tag <username>....</username>

But is it not a contradiction to that: ?!

> The displayname is not stored in a workitem as you have seen.

At the moment there are only userids in my txtworkflowhistory. I could change that but it doesn't help if I want to search for the displayName of the creator for example.

> In case you need exactly search for workitems created by 'Max Mustermann' than you can provide a extra search field using the Marty-UserInput (http://www.imixs.org/marty/ui/userinput.html). The user can first select a userid which can be used to created a structured search query.

Hm. In my case it should be possible to search for the displayName as it would be the userid because a search string is mixed with the displayName.

Maybe it's the best to split the search query, compute userids for each word and add them to the search query? No good solution but would work...

**Comment by rsoika** [comment]
When you use a random userid for security reasons, as you say, then you should not display this id to other users. So your history entries for example should not be:

`u12345345 approved request.`

but

`Max Mustermann approved request`


To avoid tese history entries you can use:

`<username>namcurrenteditor</username>  approved request.`

The plugin `org.imixs.marty.plugins.ProfilePlugin` will automatically translate the userid into the display name. 

So this would work for a general full text search. 
But if you want for example search for the creator, than your search form should allow the user to select a user (by its display name), which can be done with the Marty-userinput Widget and you should construct a structured search query.

**Comment by chrisw14** [comment]
Great! I see, you thought of everything ;-)
